export type NewsTopic = "National" | "Geopolitics" | "Economy" | "Law & Rights" | "Protest";
export type NewsItem = { id: string; title: string; summary: string; url: string; source: string; publishedAt: string | null; topic: NewsTopic };
type SourceStatus = { name: string; status: "connected" | "pending" | "error"; detail: string };
export type NewsFeed = { items: NewsItem[]; sources: SourceStatus[]; lastCheckedAt: string };

const NDTV_FEED = "https://feeds.feedburner.com/ndtvnews-latest";
let cache: { expiresAt: number; data: NewsFeed } | null = null;
const clean = (value: string) => value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, "$1").replace(/<[^>]+>/g, " ").replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\s+/g, " ").trim();
const pick = (block: string, name: string) => clean(block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`, "i"))?.[1] ?? "");
export function inferTopic(text: string): NewsTopic { const value = text.toLowerCase(); if (/(court|law|legal|police|arrest|fir|rights|judicial|supreme)/.test(value)) return "Law & Rights"; if (/(protest|demonstrat|march|rally|agitat|dharna)/.test(value)) return "Protest"; if (/(econom|market|gdp|bank|inflation|tax|trade|rupee|budget)/.test(value)) return "Economy"; if (/(world|global|foreign|china|pakistan|russia|ukraine|israel|iran|united states|us )/.test(value)) return "Geopolitics"; return "National"; }
export function parseRss(xml: string, source: string): NewsItem[] { return (xml.match(/<item\b[^>]*>[\s\S]*?<\/item>/gi) ?? []).map((block, index) => { const title = pick(block, "title"), url = pick(block, "link"), summary = pick(block, "description"), rawDate = pick(block, "pubDate"); return { id: `${source}-${url || index}`, title, url, summary, source, publishedAt: rawDate && !Number.isNaN(Date.parse(rawDate)) ? new Date(rawDate).toISOString() : null, topic: inferTopic(`${title} ${summary}`) }; }).filter((item) => Boolean(item.title && item.url)); }
export async function getLatestNews(forceRefresh = false): Promise<NewsFeed> { if (!forceRefresh && cache && Date.now() < cache.expiresAt) return cache.data; const sources: SourceStatus[] = [{ name: "NDTV", status: "connected", detail: "Official latest-headlines RSS endpoint" }, { name: "The Wire", status: "pending", detail: "Publisher feed endpoint / reuse review pending" }, { name: "Scroll", status: "pending", detail: "Publisher feed endpoint / reuse review pending" }, { name: "The Hindu", status: "pending", detail: "Directory access and reuse review pending" }]; let items: NewsItem[] = []; try { const response = await fetch(NDTV_FEED, { signal: AbortSignal.timeout(8000), headers: { "User-Agent": "Panopticon civic news monitor/1.0" } }); if (!response.ok) throw new Error(`Feed response ${response.status}`); items = parseRss(await response.text(), "NDTV").slice(0, 12); } catch { sources[0] = { name: "NDTV", status: "error", detail: "Latest feed unavailable; no headline is fabricated" }; } const data: NewsFeed = { items, sources, lastCheckedAt: new Date().toISOString() }; cache = { data, expiresAt: Date.now() + 30 * 60 * 1000 }; return data; }
